### ISSUE TITLE
Microphone issue

### ISSUE THREAD

**Issue by narcomo** [GPUCode/android_device_nokia_nb1#4]
The microphone in the latest build doesn't seem to work on third party apps (e.g. telegram, signal, duo, etc.). Voice messages are working, but video/voice calls are not.
[run.log](https://github.com/GPUCode/android_device_nokia_nb1/files/5825926/run.log)

**Comment by raphaelthegreat** [comment]
Please provide a log of your issue, without it I cannot help. Connect your phone to a PC l, run adb logcat > run.log and replicate the issue. Upload the run.log file here

**Comment by narcomo** [comment]
> Please provide a log of your issue, without it I cannot help. Connect your phone to a PC l, run adb logcat > run.log and replicate the issue. Upload the run.log file here

I've edited the post. Sorry about that.

**Comment by raphaelthegreat** [comment]
Sorry about the late response. I just had the time to look at it and it seems that the audio service crashes frequently
`01-17 12:25:02.346   760  1997 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x11211 in tid 1997 (HwBinder:760_3), pid 760 (audio.service)
01-17 12:25:02.382  1315  3740 I chatty  : uid=1000(system) Binder:1315_11 expire 1 line
01-17 12:25:02.387  1315  2639 I chatty  : uid=1000(system) uteStateMachine expire 24 lines
01-17 12:25:02.388  1315  1315 I chatty  : uid=1000 system_server expire 12 lines
01-17 12:25:02.388  1315  2636 I chatty  : uid=1000(system) BluetoothRouteM expire 2 lines
01-17 12:25:02.415 21534 21534 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-17 12:25:02.415 21534 21534 F DEBUG   : crDroid Version: '7.1'
01-17 12:25:02.415 21534 21534 F DEBUG   : Build fingerprint: 'Nokia/NB1_00WW_FIH/NB1:9/PPR1.180610.011/00WW_5_15K:user/release-keys'
01-17 12:25:02.415 21534 21534 F DEBUG   : Revision: '0'
01-17 12:25:02.415 21534 21534 F DEBUG   : ABI: 'arm'
01-17 12:25:02.417 21534 21534 F DEBUG   : Timestamp: 2021-01-17 12:25:02+0300
01-17 12:25:02.417 21534 21534 F DEBUG   : pid: 760, tid: 1997, name: HwBinder:760_3  >>> /vendor/bin/hw/android.hardware.audio.service <<<
01-17 12:25:02.417 21534 21534 F DEBUG   : uid: 1041
01-17 12:25:02.417 21534 21534 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x11211
01-17 12:25:02.417 21534 21534 F DEBUG   :     r0  ef903260  r1  00011131  r2  00000000  r3  0000002c
01-17 12:25:02.417 21534 21534 F DEBUG   :     r4  f0e40df0  r5  ef720fe0  r6  f1755124  r7  ef720f40
01-17 12:25:02.417 21534 21534 F DEBUG   :     r8  efd6edc8  r9  efd02b94  r10 f1755124  r11 ef903260
01-17 12:25:02.417 21534 21534 F DEBUG   :     ip  edad14b8  sp  edad19a8  lr  ef71dabb  pc  ef71dae0
01-17 12:25:02.441 21534 21534 F DEBUG   : backtrace:
01-17 12:25:02.442 21534 21534 F DEBUG   :       #00 pc 00005ae0  /vendor/lib/liba2dpoffload.so (a2dp_set_parameters+1064) (BuildId: 00018ceeb2cf477719a7347b06bf7494)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #01 pc 0003e134  /vendor/lib/hw/audio.primary.msm8998.so (adev_set_parameters+1960) (BuildId: 12b106af27a1410b13f157544ad5fb9e)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #02 pc 000177b5  /vendor/lib/hw/android.hardware.audio@6.0-impl.so (android::hardware::audio::V6_0::implementation::ParametersUtil::setParametersImpl(android::hardware::hidl_vec<android::hardware::audio::V6_0::ParameterValue> const&, android::hardware::hidl_vec<android::hardware::audio::V6_0::ParameterValue> const&)+268) (BuildId: 52633e9e2681bacbacc5e5bdd0d31940)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #03 pc 00015ac3  /vendor/lib/hw/android.hardware.audio@6.0-impl.so (android::hardware::audio::V6_0::implementation::Device::setParameters(android::hardware::hidl_vec<android::hardware::audio::V6_0::ParameterValue> const&, android::hardware::hidl_vec<android::hardware::audio::V6_0::ParameterValue> const&)+10) (BuildId: 52633e9e2681bacbacc5e5bdd0d31940)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #04 pc 0001813d  /vendor/lib/hw/android.hardware.audio@6.0-impl.so (android::hardware::audio::V6_0::implementation::PrimaryDevice::setParameters(android::hardware::hidl_vec<android::hardware::audio::V6_0::ParameterValue> const&, android::hardware::hidl_vec<android::hardware::audio::V6_0::ParameterValue> const&)+12) (BuildId: 52633e9e2681bacbacc5e5bdd0d31940)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #05 pc 000393f5  /apex/com.android.vndk.v30/lib/android.hardware.audio@6.0.so (android::hardware::audio::V6_0::BnHwDevice::_hidl_setParameters(android::hidl::base::V1_0::BnHwBase*, android::hardware::Parcel const&, android::hardware::Parcel*, std::__1::function<void (android::hardware::Parcel&)>)+332) (BuildId: b69b9f55a6e6c4d720e08033c7d1c910)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #06 pc 00050e95  /apex/com.android.vndk.v30/lib/android.hardware.audio@6.0.so (android::hardware::audio::V6_0::BnHwPrimaryDevice::onTransact(unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int, std::__1::function<void (android::hardware::Parcel&)>)+1964) (BuildId: b69b9f55a6e6c4d720e08033c7d1c910)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #07 pc 0006a033  /apex/com.android.vndk.v30/lib/libhidlbase.so (android::hardware::BHwBinder::transact(unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int, std::__1::function<void (android::hardware::Parcel&)>)+46) (BuildId: 2a6b1573578f891efde26cccafcc488a)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #08 pc 0006caa3  /apex/com.android.vndk.v30/lib/libhidlbase.so (android::hardware::IPCThreadState::getAndExecuteCommand()+962) (BuildId: 2a6b1573578f891efde26cccafcc488a)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #09 pc 0006d87d  /apex/com.android.vndk.v30/lib/libhidlbase.so (android::hardware::IPCThreadState::joinThreadPool(bool)+64) (BuildId: 2a6b1573578f891efde26cccafcc488a)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #10 pc 00079349  /apex/com.android.vndk.v30/lib/libhidlbase.so (android::hardware::PoolThread::threadLoop()+12) (BuildId: 2a6b1573578f891efde26cccafcc488a)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #11 pc 0000ee95  /apex/com.android.vndk.v30/lib/libutils.so (android::Thread::_threadLoop(void*)+168) (BuildId: 44474b90f2203be44b6b22ca4bf56b47)
01-17 12:25:02.442 21534 21534 F DEBUG   :       #12 pc 0000e9dd  /apex/com.android.vndk.v30/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+256) (BuildId: 44474b90f2203be44b6b22ca4bf56b47)`

I think this is caused by the switch from 5.0 audio HAL to 6.0. I will revert back to version 5.0 and test in my next build.
